### ISSUE TITLE
deployment Issues

### ISSUE THREAD

**Issue by mr-kunal-07** [sharmavikas4/MERN_BLOG#6]
Hi @KiranBaliga  & @sharmavikas4 
I come to this repo and found issues regarding deployment , its not opning on vercel, let me work on that I know how to fix 

issue Discription :- 
![image](https://github.com/user-attachments/assets/19835916-b9d9-421f-bbd6-fa344ffbb3e6)
click on link it will show
![image](https://github.com/user-attachments/assets/9fb9f461-8d55-40ec-9a37-270c9c69e3a1)
its showing connect get 
i can make it proper

**Comment by sharmavikas4** [comment]
@mr-kunal-07 you can proceed with fixing the deployment. For your reference, I can tell you that there is an issue that the app does not open when deployed externally, although it works fine on the local system, due to the cookies getting lost.

**Comment by mr-kunal-07** [comment]
I know how to fix this problem....

**Comment by sharmavikas4** [comment]
Go ahead @mr-kunal-07

**Comment by mr-kunal-07** [comment]
Yes

**Comment by VarunChopra11** [comment]
i noticed that this issue is opened from last 2 days and yet didn't get resolved @sharmavikas4 please assign the above issue to me. If its available or open.

I just tried its deployment and **voila** got it here's the link go check it : https://mern-blog-flame.vercel.app/
Just ignore its backend activities for now because for that i require its **envs** but yeah the frontend part is deployed, please specify where is you backend deployed or is it stiil to be deployed just assign me the issue and provide requirements, i will be on to it.

**Comment by sharmavikas4** [comment]
@mr-kunal-07 what is the progress so far.

**Comment by mr-kunal-07** [comment]
Last thing left 
I will finish by today

**Comment by sharmavikas4** [comment]
@mr-kunal-07 are you done with deployment

**Comment by sharmavikas4** [comment]
@mr-kunal-07 are you done with deployment or shall i assign it to someone else

**Comment by sharmavikas4** [comment]
@mr-kunal-07 shall i close this issue if you are not working

**Comment by VarunChopra11** [comment]
> @mr-kunal-07 shall i close this issue if you are not working

Can i work on it ? Please assign me the issue.

**Comment by sharmavikas4** [comment]
@VarunChopra11 you can proceed

**Comment by VarunChopra11** [comment]
Hey, I'm having some questions regarding the issue let's connect on discord for clarification here's my tag: varunchopra11
Please send a request or share your discord tag.
